# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crmod.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CRModWindow(object):
    def setupUi(self, CRModWindow):
        CRModWindow.setObjectName("CRModWindow")
        CRModWindow.resize(419, 267)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("up-to-pypi-main/up_to_pypi/images/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CRModWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CRModWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.module_version = QtWidgets.QLineEdit(self.centralwidget)
        self.module_version.setObjectName("module_version")
        self.gridLayout.addWidget(self.module_version, 1, 1, 1, 1)
        self.author = QtWidgets.QLineEdit(self.centralwidget)
        self.author.setObjectName("author")
        self.gridLayout.addWidget(self.author, 4, 0, 1, 1)
        self.build_files = QtWidgets.QPushButton(self.centralwidget)
        self.build_files.setEnabled(False)
        self.build_files.setObjectName("build_files")
        self.gridLayout.addWidget(self.build_files, 9, 0, 1, 2)
        self.repo_url = QtWidgets.QLineEdit(self.centralwidget)
        self.repo_url.setObjectName("repo_url")
        self.gridLayout.addWidget(self.repo_url, 3, 1, 1, 1)
        self.author_email = QtWidgets.QLineEdit(self.centralwidget)
        self.author_email.setObjectName("author_email")
        self.gridLayout.addWidget(self.author_email, 4, 1, 1, 1)
        self.module_name = QtWidgets.QLineEdit(self.centralwidget)
        self.module_name.setObjectName("module_name")
        self.gridLayout.addWidget(self.module_name, 1, 0, 1, 1)
        self.choose_location = QtWidgets.QPushButton(self.centralwidget)
        self.choose_location.setObjectName("choose_location")
        self.gridLayout.addWidget(self.choose_location, 7, 0, 1, 2)
        self.description = QtWidgets.QLineEdit(self.centralwidget)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 3, 0, 1, 1)
        CRModWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CRModWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 22))
        self.menubar.setObjectName("menubar")
        CRModWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CRModWindow)
        self.statusbar.setObjectName("statusbar")
        CRModWindow.setStatusBar(self.statusbar)
        self.actionChoose_Location = QtWidgets.QAction(CRModWindow)
        self.actionChoose_Location.setObjectName("actionChoose_Location")
        self.actionBuild_Files = QtWidgets.QAction(CRModWindow)
        self.actionBuild_Files.setObjectName("actionBuild_Files")
        self.actionClear_Text_Fields = QtWidgets.QAction(CRModWindow)
        self.actionClear_Text_Fields.setObjectName("actionClear_Text_Fields")
        self.actionAbout_Module_Creator = QtWidgets.QAction(CRModWindow)
        self.actionAbout_Module_Creator.setObjectName("actionAbout_Module_Creator")

        self.retranslateUi(CRModWindow)
        QtCore.QMetaObject.connectSlotsByName(CRModWindow)

    def retranslateUi(self, CRModWindow):
        _translate = QtCore.QCoreApplication.translate
        CRModWindow.setWindowTitle(_translate("CRModWindow", "Module Creater"))
        self.module_version.setPlaceholderText(_translate("CRModWindow", "Module Version"))
        self.author.setPlaceholderText(_translate("CRModWindow", "Author Name"))
        self.build_files.setText(_translate("CRModWindow", "Build Files"))
        self.repo_url.setPlaceholderText(_translate("CRModWindow", "URL"))
        self.author_email.setPlaceholderText(_translate("CRModWindow", "Author Email"))
        self.module_name.setPlaceholderText(_translate("CRModWindow", "Module Name"))
        self.choose_location.setText(_translate("CRModWindow", "Choose Location"))
        self.description.setPlaceholderText(_translate("CRModWindow", "Small Description"))
        self.actionChoose_Location.setText(_translate("CRModWindow", "Choose Location"))
        self.actionBuild_Files.setText(_translate("CRModWindow", "Build Files"))
        self.actionClear_Text_Fields.setText(_translate("CRModWindow", "Clear Text Fields"))
        self.actionAbout_Module_Creator.setText(_translate("CRModWindow", "About Module Creator"))
